# [1차 설정] - Certbot 인증서 발급용
server {
    listen 80;
    server_name hirepicker.duckdns.org; # <-- 네 DuckDNS 도메인

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 404; # 일단 다른 요청은 막음
    }
}