export function createEmptyResumeForm() {
  return {
    title: "",
    name: "",
    gender: "",
    birthdate: "",
    phone: "",
    email: "",
    address: "",
    aiPrompt: "",
    selfGrowth: "",
    selfStrengths: "",
    selfMotivation: "",
    selfAspirations: "",
    creditCost: 0,
    resumeStatus: "PRIVATE",
    // 학력 1
    edu1_school: "",
    edu1_schoolCode: null,
    edu1_major: "",
    edu1_status: "",
    edu1_score: "",
    edu1_admission: "",
    edu1_graduation: "",
    edu1_period: "",
    // 학력 2
    edu2_school: "",
    edu2_schoolCode: null,
    edu2_major: "",
    edu2_status: "",
    edu2_score: "",
    edu2_admission: "",
    edu2_graduation: "",
    edu2_period: "",
    // 병역
    military_status: "",
    military_branch: "",
    military_rank: "",
    military_enlistment: "",
    military_discharge: "",
    military_reason: "",
    military_period: "",
    // 자격증
    cert1_name: "",
    cert1_score: "",
    cert2_name: "",
    cert2_score: "",
    cert3_name: "",
    cert3_score: "",
    // 경력 1
    exp1_period: "",
    exp1_company: "",
    exp1_position: "",
    exp1_duties: "",
    exp1_type: "",
    exp1_hire: "",
    exp1_resign: "",
    // 경력 2
    exp2_period: "",
    exp2_company: "",
    exp2_position: "",
    exp2_duties: "",
    exp2_type: "",
    exp2_hire: "",
    exp2_resign: "",
  };
}

