name: HIREPICKER CI/CD

on:
  push:
    branches: ["dev"]

env:
  BACKEND_IMAGE: hirepicker-backend
  FRONTEND_IMAGE: hirepicker-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hirepicker-backend:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/hirepicker-backend:latest

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hirepicker-frontend:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/hirepicker-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Transfer config files to EC2
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          source: "docker-compose.yml,nginx.conf"
          target: "/home/ubuntu/hirepicker"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/ubuntu/hirepicker

            # 1. DB 비번 등이 담긴 .env 파일 생성
            echo "${{ secrets.DOT_ENV }}" > .env

            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
            echo "BACKEND_IMAGE=${{ env.BACKEND_IMAGE }}" >> .env
            echo "FRONTEND_IMAGE=${{ env.FRONTEND_IMAGE }}" >> .env

            # 3. Docker 로그인
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # 4. 이전 컨테이너 중지 및 삭제
            docker compose --profile prod down --remove-orphans

            # 5. 불필요한 이미지 정리
            docker container prune -f
            docker image prune -a -f

            # 6. 새 이미지 pull 및 컨테이너 시작
            #    (이제 docker-compose.yml이 .env 파일에서 변수를 잘 읽어올 거야)
            docker compose --profile prod --env-file ./.env pull
            docker compose --profile prod --env-file ./.env up -d